### ISSUE TITLE
Remove unused Python import statements

### ISSUE THREAD

**Issue by eoaksnes** [equinor/template-fastapi-react#31]
Option 1:

[autoflake](https://github.com/PyCQA/autoflake) removes unused imports and unused variables from Python code. It makes use of [pyflakes](http://pypi.python.org/pypi/pyflakes) to do this. 

Example:

```
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
```
Option 2:

[pycln](https://github.com/hadialqattan/pycln): a formatter for finding and removing unused import statements

Example:

```
-   repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
```

Maybe there exist other options also...
